version: 2
updates:
  # Go backend dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "deps(go)"
      include: "scope"
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    commit-message:
      prefix: "deps(frontend)"
    groups:
      vue-ecosystem:
        patterns:
          - "vue*"
          - "@vue/*"
          - "vite*"
          - "@vitejs/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  
  # Extension dependencies
  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    commit-message:
      prefix: "deps(extension)"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"