# Minimal golangci-lint configuration for GitHub Actions compatibility  
version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell