# Minimal golangci-lint configuration for GitHub Actions compatibility
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell

issues:
  max-issues-per-linter: 50
  max-same-issues: 10