name: Extension CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'extension/**'
      - '.github/workflows/extension.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'extension/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: extension/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate manifest
      run: |
        echo "Validating manifest.json structure..."
        node -e "
          const manifest = require('./manifest.json');
          if (!manifest.name || !manifest.version || !manifest.manifest_version) {
            throw new Error('Invalid manifest structure');
          }
          console.log('Manifest validation passed');
        "
    
    - name: Lint extension files
      run: |
        # Basic file validation
        echo "Checking required extension files..."
        test -f manifest.json || (echo "manifest.json missing" && exit 1)
        test -f popup.html || (echo "popup.html missing" && exit 1)
        test -f popup.js || (echo "popup.js missing" && exit 1)
        test -f background.js || (echo "background.js missing" && exit 1)
        echo "All required files present"
    
    - name: Build extension
      run: |
        mkdir -p build
        cp -r *.js *.html *.json *.png build/
        echo "Extension built successfully"
    
    - name: Upload extension artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: extension/build/
        retention-days: 30